---
# cloud-config
users:
  - default
  - name: kubernetes
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
    lock_passwd: false

package_update: true

write_files:
  - path: /etc/k3s-config.yaml
    content: |
      server: https://${cluster_vip}:6443
      token: ${k3s_token}
      node-ip: ${node_ip}
      flannel-iface: eth0
    owner: root:root
    permissions: '0644'

  - path: /usr/local/bin/setup-k3s.sh
    content: |
      #!/bin/bash
      set -e

      # Wait for control plane to be ready
      while ! nc -z ${cluster_vip} 6443; do
        echo "Waiting for control plane to be ready..."
        sleep 10
      done

      # Install k3s agent
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${k3s_version} sh -s - agent --config /etc/k3s-config.yaml

      echo "K3s worker node setup completed"
    owner: root:root
    permissions: '0755'

runcmd:
  - /usr/local/bin/setup-k3s.sh

final_message: "K3s worker node is ready!"
