---
# cloud-config
users:
  - default
  - name: kubernetes
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
    lock_passwd: false

package_update: true

write_files:
  - path: /etc/k3s-config.yaml
    content: |
      cluster-init: true
      token: ${k3s_token}
      disable:
        - traefik
        - servicelb
      kube-apiserver-arg:
        - advertise-address=${node_ip}
      node-ip: ${node_ip}
      bind-address: ${node_ip}
      flannel-iface: eth0
      tls-san:
        - ${cluster_vip}
        - ${node_ip}
    owner: root:root
    permissions: '0644'
  
  - path: /etc/kube-vip.yml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        creationTimestamp: null
        name: kube-vip
        namespace: kube-system
      spec:
        containers:
        - args:
          - manager
          env:
          - name: vip_arp
            value: "true"
          - name: port
            value: "6443"
          - name: vip_interface
            value: eth0
          - name: vip_cidr
            value: "32"
          - name: cp_enable
            value: "true"
          - name: cp_namespace
            value: kube-system
          - name: vip_ddns
            value: "false"
          - name: svc_enable
            value: "true"
          - name: vip_leaderelection
            value: "true"
          - name: vip_leaseduration
            value: "5"
          - name: vip_renewdeadline
            value: "3"
          - name: vip_retryperiod
            value: "1"
          - name: address
            value: ${cluster_vip}
          image: ghcr.io/kube-vip/kube-vip:v0.8.7
          imagePullPolicy: Always
          name: kube-vip
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              - SYS_TIME
          volumeMounts:
          - mountPath: /etc/kubernetes/admin.conf
            name: kubeconfig
          - mountPath: /etc/hosts
            name: etchosts
        hostAliases:
        - hostnames:
          - kubernetes
          ip: 127.0.0.1
        hostNetwork: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/admin.conf
          name: kubeconfig
        - hostPath:
            path: /etc/hosts
          name: etchosts
      status: {}
    owner: root:root
    permissions: '0644'

  - path: /usr/local/bin/setup-k3s.sh
    content: |
      #!/bin/bash
      set -e

      # Install k3s
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${k3s_version} sh -s - server --config /etc/k3s-config.yaml

      # Wait for k3s to be ready
      while ! kubectl get nodes >/dev/null 2>&1; do
        echo "Waiting for k3s to be ready..."
        sleep 5
      done

      # Deploy kube-vip
      mkdir -p /var/lib/rancher/k3s/server/manifests
      cp /etc/kube-vip.yml /var/lib/rancher/k3s/server/manifests/

      echo "K3s with kube-vip setup completed"
    owner: root:root
    permissions: '0755'

runcmd:
  - /usr/local/bin/setup-k3s.sh

final_message: "K3s control plane with kube-vip is ready!"
